Repository HMDandelion/project1-4-1000-2_front, pull requests merged in 2024-06, with the labels that each got.

#2 [PR] 거래처 목록 조회
  package-lock.json
  package.json
  src/App.js
  src/apis/ClientAPICalls.js
  src/apis/api.js
  src/components/SidebarContent.js
  src/components/card/Card.js
  src/components/icons/Icons.js
  src/components/table/ComplexTable.js
  src/index.js
  src/layouts/AdminLayout.js
  src/modules/ClientModules.js
  src/modules/index.js
  src/pages/sales/client/Clients.js
Labels: feature

#10 [PR]상품 및 재고 기능
  .env
  package-lock.json
  package.json
  src/App.js
  src/Products.css
  src/apis/ProductAPICalls.js
  src/apis/StockAPICalls.js
  src/apis/StorageAPICalls.js
  src/apis/WarehouseAPICalls.js
  src/chart/Chart.js
  src/chart/DestroyRatio.js
  src/chart/StockRatio.js
  src/components/SidebarContent.js
  src/components/table/productTable/CustomizedTable.js
  src/modals/products/BomSave.js
  src/modals/products/BomUpdate.js
  src/modals/products/ProductClient.js
  src/modals/products/ProductSave.js
  src/modals/products/ProductUpdate.js
  src/modals/products/SpecSave.js
  src/modals/products/SpecUpdate.js
  src/modals/products/StockUpdate.js
  src/modals/products/WarehouseAssignment.js
  src/modules/ProductModules.js
  src/modules/StockModules.js
  src/modules/StorageModules.js
  src/modules/WarehouseModules.js
  src/modules/index.js
  src/pages/inventory/product/ProductDetail.js
  src/pages/inventory/product/Products.js
  src/pages/inventory/warehouse/Warehouses.js
Labels: feature

#13 [PR] 원자재 조회 페이지
  src/App.js
  src/apis/ClientAPICalls.js
  src/apis/MaterialOrderAPICalls.js
  src/apis/MaterialSpecAPICalls.js
  src/apis/MaterialStockAPICalls.js
  src/apis/MaterialUsageAPICalls.js
  src/components/Navbar.js
  src/components/SidebarContent.js
  src/components/common/DropDownMenu.js
  src/modules/ClientModules.js
  src/modules/MaterialOrderModules.js
  src/modules/MaterialSpecModules.js
  src/modules/MaterialStockDDModules.js
  src/modules/MaterialStockModules.js
  src/modules/MaterialUsageModules.js
  src/modules/index.js
  src/pages/inventory/material/InventoryMaterailAnalyze.js
  src/pages/inventory/material/MaterialInStock.js
  src/pages/inventory/material/MaterialStocks.js
  src/pages/inventory/material/Specs.js
  src/pages/production/material/MaterialUsages.js
  src/pages/purchase/material/MaterialClients.js
  src/pages/purchase/material/MaterialOrders.js
Labels: feature

#15 [PR] 창고 관련 페이지 기능 구현
  package-lock.json
  package.json
  src/App.js
  src/apis/ProductAPICalls.js
  src/apis/StorageAPICalls.js
  src/apis/WarehouseAPICalls.js
  src/modals/products/BomSave.js
  src/modals/products/BomUpdate.js
  src/modals/products/CancelAssignment.js
  src/modals/products/DestroyRegist.js
  src/modals/products/ProductSave.js
  src/modals/products/ProductUpdate.js
  src/modals/products/SpecSave.js
  src/modals/products/SpecUpdate.js
  src/modals/products/StockUpdate.js
  src/modals/products/StoreStock.js
  src/modals/products/WarehouseAssignment.js
  src/modals/products/WarehouseSave.js
  src/modals/products/WarehouseUpdate.js
  src/modules/ProductModules.js
  src/modules/StorageModules.js
  src/modules/WarehouseModules.js
  src/pages/inventory/product/ProductDetail.js
  src/pages/inventory/product/Products.js
  src/pages/inventory/warehouse/Warehouses.js
Labels: feature

#22 [PR] Chakra UI 버전 업
  package.json
  src/components/common/SelectMenu.js
Labels: enhancement

#17 [PR] 원자재 상세조회 페이지
  src/App.js
  src/apis/ClientAPICalls.js
  src/apis/MaterialOrderAPICalls.js
  src/apis/MaterialSpecAPICalls.js
  src/apis/MaterialStockAPICalls.js
  src/components/SidebarContent.js
  src/components/button/SetMaterialOrderButton.js
  src/modules/MaterialOrderModules.js
  src/modules/MaterialSpecModules.js
  src/modules/MaterialStockModules.js
  src/pages/inventory/material/MaterialStocks.js
  src/pages/inventory/material/SpecDetail.js
  src/pages/inventory/material/Specs.js
  src/pages/inventory/material/StockDetail.js
  src/pages/purchase/material/MaterialClientDetail.js
  src/pages/purchase/material/MaterialClients.js
  src/pages/purchase/material/MaterialOrderDetail.js
  src/pages/purchase/material/MaterialOrders.js
Labels: bug, enhancement, feature

#19 [PR] 견적 도메인 페이지 구현
  package-lock.json
  package.json
  src/App.js
  src/apis/AuthAPICalls.js
  src/apis/ClientAPICalls.js
  src/apis/EstimateAPICalls.js
  src/apis/OrderAPICalls.js
  src/apis/ProductAPICalls.js
  src/assets/css/MiniCalendar.css
  src/components/Navbar.js
  src/components/NavbarLinks.js
  src/components/badge/OrderStatusBadge.js
  src/components/button/OrderRegistButton.js
  src/components/calendar/MiniCalendar.js
  src/components/calendar/PopoverCalendar.js
  src/modules/AuthModules.js
  src/modules/ClientModules.js
  src/modules/EstimateModules.js
  src/modules/OrderModules.js
  src/modules/ProductModules.js
  src/modules/index.js
  src/pages/sales/client/ClientModify.js
  src/pages/sales/client/ClientRegist.js
  src/pages/sales/estimate/ClientSelectForm.js
  src/pages/sales/estimate/EstimateDetail.js
  src/pages/sales/estimate/EstimateForm.js
  src/pages/sales/estimate/EstimateModify.js
  src/pages/sales/estimate/EstimateRegist.js
  src/pages/sales/estimate/Estimates.js
  src/pages/sales/estimate/PriceAndQuantityForm.js
  src/pages/sales/estimate/ProductSelectForm.js
  src/pages/sales/order/OrderDetail.js
  src/pages/sales/order/Orders.js
  src/pages/test.js
  src/utils/TokenUtils.js
Labels: enhancement, feature

#25 [PR] import 누락 문제 해결
  package-lock.json
  src/apis/ClientAPICalls.js
Labels: bug

#27 [PR] 재고 관련 페이지 및 기능 구현
  package-lock.json
  src/App.js
  src/apis/ReleaseAPICalls.js
  src/apis/WarehouseAPICalls.js
  src/components/Navbar.js
  src/components/SidebarContent.js
  src/components/button/CompleteAlertButton.js
  src/components/button/ReleaseAlertButton.js
  src/components/button/ShippingAlertButton.js
  src/components/icons/ArrowIcon.js
  src/components/table/product/CustomizedTable.js
  src/components/table/product/ReleaseWaitTable.js
  src/modules/ReleaseModules.js
  src/modules/index.js
  src/pages/inventory/product/ProductDetail.js
  src/pages/inventory/product/Products.js
  src/pages/inventory/release/Release.js
  src/pages/inventory/release/ReleaseCompleteTable.js
  src/pages/inventory/release/ReleaseOrder.js
  src/pages/inventory/release/ReleaseShippingTable.js
  src/pages/inventory/warehouse/Warehouses.js
  src/theme/components/modals/products/BomSave.js
  src/theme/components/modals/products/BomUpdate.js
  src/theme/components/modals/products/CancelAssignment.js
  src/theme/components/modals/products/DestroyRegist.js
  src/theme/components/modals/products/ProductClient.js
  src/theme/components/modals/products/ProductSave.js
  src/theme/components/modals/products/ProductUpdate.js
  src/theme/components/modals/products/SpecSave.js
  src/theme/components/modals/products/SpecUpdate.js
  src/theme/components/modals/products/StockUpdate.js
  src/theme/components/modals/products/StoreStock.js
  src/theme/components/modals/products/WarehouseAssignment.js
  src/theme/components/modals/products/WarehouseSave.js
  src/theme/components/modals/products/WarehouseUpdate.js
  src/theme/components/modals/release/OrderInformation.js
  src/theme/components/modals/release/OrderProduct.js
  src/theme/components/modals/release/ReleaseExpected.js
  src/theme/components/modals/release/ReleaseLack.js
Labels: feature

#33 [PR] 생산 계획
  package.json
  src/App.js
  src/apis/ClientAPICalls.js
  src/apis/OrderAPICalls.js
  src/apis/PlanningAPICalls.js
  src/apis/WorkOrderAPICalls.js
  src/components/CommonStatusChanger.js
  src/components/Navbar.js
  src/components/SidebarContent.js
  src/components/badge/WorkOrderStatusBadge.js
  src/components/footer/FooterAdmin.js
  src/layouts/AdminLayout.js
  src/modules/PlanningModules.js
  src/modules/PlanningOrderModules.js
  src/modules/WorkOrderModules.js
  src/modules/index.js
  src/pages/Production/plan/CalendarPlan.js
  src/pages/Production/plan/CalendarPlans.js
  src/pages/Production/plan/CustomEventComponent.js
  src/pages/Production/plan/CustomToolbar.js
  src/pages/Production/plan/PlanCalendar.js
  src/pages/Production/plan/PlanForm.js
  src/pages/Production/plan/PlanModify.js
  src/pages/Production/plan/PlanOrderDetail.js
  src/pages/Production/plan/PlanRegist.js
  src/pages/Production/plan/Plans.js
  src/pages/Production/workOrder/RegistLines.js
  src/pages/Production/workOrder/WorkOrderForm.js
  src/pages/Production/workOrder/WorkOrderList.js
  src/pages/Production/workOrder/WorkOrderModify.js
  src/pages/Production/workOrder/WorkOrderRegist.js
  src/pages/Production/workOrder/WorkOrders.js
  src/pages/production/material/MaterialUsages.js
  src/util/TokenUtils.js
Labels: feature

#30 [PR] 인증/인가 예외 핸들링
  src/App.js
  src/apis/AuthAPICalls.js
  src/apis/api.js
  src/components/NavbarLinks.js
  src/index.js
  src/modules/AuthModules.js
  src/modules/NavigationModules.js
  src/modules/index.js
  src/pages/auth/LogIn.js
Labels: enhancement

#35 [PR] 로그인 설정 및 디자인 보강,기능 추가 구현
  package.json
  src/App.js
  src/Products.css
  src/apis/ProductAPICalls.js
  src/apis/ReleaseAPICalls.js
  src/apis/StockAPICalls.js
  src/apis/StorageAPICalls.js
  src/apis/WarehouseAPICalls.js
  src/chart/DestroyRatio.js
  src/chart/StockRatio.js
  src/pages/inventory/product/Products.js
  src/pages/inventory/warehouse/Warehouses.js
Labels: enhancement, feature

#36 [PR] 파비콘 추가
  public/index.html
  public/일사천리.png
Labels: enhancement

#37 [PR] 사이트 이름 추가
  public/index.html
Labels: enhancement

#39 [PR] 대시보드 디자인
  public/ilsaheonli.png
  public/index.html
  src/components/SidebarBrand.js
  src/pages/TestPage.css
  src/pages/test.js
Labels: enhancement

#38 [PR] 생산 조회 및 등록
  package-lock.json
  src/App.js
  src/apis/ProductionAPICalls.js
  src/components/SidebarContent.js
  src/modules/ProductionReportModules.js
  src/modules/index.js
  src/pages/production/productionReport/DefectDetail.js
  src/pages/production/productionReport/DefectDetailForm.js
  src/pages/production/productionReport/ProductionDetailForm.js
  src/pages/production/productionReport/ProductionReportDetail.js
  src/pages/production/productionReport/ProductionReportForm.js
  src/pages/production/productionReport/ProductionReportRegist.js
  src/pages/production/productionReport/ProductionReports.js
  src/pages/sales/client/ClientForm.js
Labels: feature
